/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import config.Conexion;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane; 
import java.util.ArrayList;


/**
 *
 * @author Marcos
 */
public class Venta extends javax.swing.JInternalFrame {

    Conexion con=new Conexion();
    Connection cn;
    Statement st = null;
    ResultSet rs = null;
    
    
    DefaultTableModel model;
    int id; // para modificar un id
   
    
   
    
    
    
    
    
    public Venta() {
        initComponents();
      listar();
     
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        nom_cliente = new javax.swing.JTextField();
        codigo_cliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        reg_factura = new javax.swing.JButton();
        num_factura = new javax.swing.JTextField();
        fecha_fact = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cant_art = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        articulo_venta = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        preciu_unid = new javax.swing.JTextField();
        stock_art = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nom_empleado = new javax.swing.JTextField();
        Total_art = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaFactu = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaFactu1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        cod_factura = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cod_producto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Datos de Venta");

        jButton1.setText("Registrar Detalles");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("id cliente");

        jLabel11.setText("Nombre cliente");

        jLabel5.setText("Num factura");

        reg_factura.setText("Registrar Factura");
        reg_factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_facturaActionPerformed(evt);
            }
        });

        num_factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_facturaActionPerformed(evt);
            }
        });

        jLabel10.setText("Fecha");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Cantidad");

        cant_art.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cant_artActionPerformed(evt);
            }
        });
        cant_art.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cant_artKeyReleased(evt);
            }
        });

        jLabel15.setText("Articulo");

        jLabel16.setText("Precio_unidad");

        jLabel9.setText("stock");

        jLabel2.setText("Nombre empleado");

        nom_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_empleadoActionPerformed(evt);
            }
        });

        jLabel13.setText("Total articulos");

        TablaDatos.setBackground(new java.awt.Color(153, 255, 153));
        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "nombre", "precio", "plataforma", "stock", "genero"
            }
        ));
        TablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDatos);

        TablaFactu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Cliente", "Empleado", "Fecha"
            }
        ));
        TablaFactu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaFactuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaFactu);

        TablaFactu1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod-Factura", "cod-producto", "Producto", "Cantidad", "Precio", "Total"
            }
        ));
        TablaFactu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaFactu1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TablaFactu1);

        jLabel4.setText("Num factura");

        jLabel6.setText("id producto");

        cod_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cod_productoActionPerformed(evt);
            }
        });

        jLabel7.setText("Seleccione el articulo");

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(codigo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reg_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(282, 282, 282))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(num_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(172, 172, 172)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(nom_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addGap(21, 21, 21)
                        .addComponent(nom_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(146, 146, 146)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(106, 106, 106)
                                    .addComponent(jLabel15))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(48, 48, 48)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cod_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cod_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(articulo_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(51, 51, 51)
                                    .addComponent(jLabel9))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(18, 18, 18)
                                    .addComponent(cant_art, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(stock_art, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(51, 51, 51)
                                    .addComponent(jLabel13)
                                    .addGap(18, 18, 18)
                                    .addComponent(Total_art, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(51, 51, 51)
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(preciu_unid, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fecha_fact, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(num_factura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(nom_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(reg_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(fecha_fact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nom_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(articulo_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(stock_art, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preciu_unid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(Total_art, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(cant_art, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel4)
                    .addComponent(cod_factura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cod_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(28, 28, 28)
                        .addComponent(jButton2)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
       
        
        DetalleFactura();
         modificar();
         
        
        listacabecera();
        
        listafactura();
       
       
      
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void reg_facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_facturaActionPerformed
    RegistrarFactura();      
    }//GEN-LAST:event_reg_facturaActionPerformed

    private void cant_artActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cant_artActionPerformed

    }//GEN-LAST:event_cant_artActionPerformed

    private void cant_artKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cant_artKeyReleased
       

    }//GEN-LAST:event_cant_artKeyReleased

    
    private void nom_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_empleadoActionPerformed

    private void TablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosMouseClicked
     int fila=TablaDatos.getSelectedRow();
        if(fila == -1){

            JOptionPane.showMessageDialog(null,"Registro no seleccionado");

        }else {
            
            String nom=(String)TablaDatos.getValueAt(fila,1);
            Integer precio=(Integer)TablaDatos.getValueAt(fila,2);
            
            Integer stock=(Integer)TablaDatos.getValueAt(fila,4);
            
            
            
            
            
            articulo_venta.setText(""+nom);
            preciu_unid.setText(""+precio);
            stock_art.setText(""+stock);
            

        }

    }//GEN-LAST:event_TablaDatosMouseClicked

    private void TablaFactuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaFactuMouseClicked

        /*
        
        int fila=TablaFactu.getSelectedRow();
        if(fila == -1){

            JOptionPane.showMessageDialog(null,"Registro no seleccionado");

        }else {
            
            String cli=(String)TablaFactu.getValueAt(fila,1);
            String pro=(String)TablaFactu.getValueAt(fila,2);
            String can=(String)TablaFactu.getValueAt(fila,3);
            String sto=(String)TablaFactu.getValueAt(fila,4);
            Integer pre=(Integer)TablaFactu.getValueAt(fila,5);
            String fe=(String)TablaFactu.getValueAt(fila,6);
            Integer total=(Integer)TablaFactu.getValueAt(fila,7);

            nom_cliente.setText(""+cli);
            articulo_venta.setText(""+pro);
            cant_art.setText(""+can);
            stock_art.setText(""+sto);
            preciu_unid.setText(""+pre);
            fecha_fact.setText(""+fe);
            Total_art.setText(""+total);

        }
       */
    }//GEN-LAST:event_TablaFactuMouseClicked

      
    
    
    private void TablaFactu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaFactu1MouseClicked
        
       
        
        
        
        
        
    }//GEN-LAST:event_TablaFactu1MouseClicked

    private void cod_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cod_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cod_productoActionPerformed

    private void num_facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_facturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_facturaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    
    
    
    

      







    
    
    
    
     void RegistrarFactura(){
        
          String factura=num_factura.getText();
         String empleado=nom_empleado.getText();
        String codigocliente=codigo_cliente.getText();
        String fecha=fecha_fact.getText();
      
        
        if(factura.equals("")||codigocliente.equals("")||empleado.equals("")||fecha.equals("")){
        
        JOptionPane.showMessageDialog(null,"¡debe llenar todos los campos!");
        
        
        }else{
        String sql="insert into cabecerafactura(cod_factura,CodigoCliente,NombreEmpleado,Fecha)values('"+factura+"','"+codigocliente+"','"+empleado+"','"+fecha+"')";
            try{
            
            cn=con.getConnection();
            st=cn.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Registrado");
            
            
            } catch (SQLException e){
            
            System.err.print("Error:"+e);
            
            }
        
        
        }
        
        
    }
     
     
     void DetalleFactura(){
     
        String factura=cod_factura.getText();
        String cod_produ=cod_producto.getText();
        String nom_produc=articulo_venta.getText();
        String stock=stock_art.getText();
        String precio=preciu_unid.getText();
        String cantidad=cant_art.getText();
        String total=Total_art.getText();
        
      
        
        if(factura.equals("")||cod_produ.equals("")||nom_produc.equals("")||stock.equals("")||precio.equals("")||cantidad.equals("")||total.equals("")){
        
        JOptionPane.showMessageDialog(null,"¡debe llenar todos los campos!");
        
        
        }else{
       
         String sql="INSERT INTO `factura` (`cod_factura`, `cod_producto`,`Nom_producto`, `cantidad`, `precio`, `total`) VALUES ('"+factura+"', '"+cod_produ+"','"+nom_produc+"', '"+cantidad+"', '"+precio+"', '"+total+"')";
            try{
            
            cn=con.getConnection();
            st=cn.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Registrado");
            
            
            } catch (SQLException e){
            
            System.err.print("Error:"+e);
            
            }
        
        
        }
     
     
     
     
     
     
     }
    
     
     
     void modificar(){
    
    
    String precio=preciu_unid.getText();
    String cantidad=cant_art.getText();
    String stock=stock_art.getText();
    
    
    
    String sql="update videojuegos set precio_venta='"+precio+"',stock='"+stock+"',cantidad='"+cantidad+"' where id_juegos="+id;
    try {
            if (precio!= null||stock!=null) {
                 
                cn=con.getConnection();
                st=cn.createStatement();
                st.executeUpdate(sql);
                
                limpiartabla(model);
                
            } else {
                JOptionPane.showMessageDialog(null, "Error...!!!");
            }

        } catch (HeadlessException | SQLException e) {
            
            System.err.print("Error:"+e);
        }
    
    
    
    }
     
     
     
     
     
     
     
     
     
     
    
    
    
    
    
     void listar(){
    String sql="select * from videojuegos";
    
    try{
    
    cn=con.getConnection(); //la variable y metodo
    st=cn.createStatement();
     rs=st.executeQuery(sql);//ejecuta la consulta
     
     Object[]videojuegos=new Object[7]; // el 7 son los campos que contiene la tabla en la bd
     model = (DefaultTableModel)TablaDatos.getModel();
     
     while (rs.next()){
     
      videojuegos[0] = rs.getInt("id_juegos");
      videojuegos[1]=rs.getString("nombre");
      videojuegos[2]=rs.getInt("precio_venta");
      videojuegos[3]=rs.getString("plataforma");
      videojuegos[4] =rs.getInt("stock");
      videojuegos[5] =rs.getString("genero");
      videojuegos[6] =rs.getString("id_proveedor");
      
      
      model.addRow(videojuegos);
      
     
     }
     
     TablaDatos.setModel(model);
     
     
    } catch (SQLException e){
    
  System.err.print("Error:"+e);
    
    }
    
    }
     
     
     
     
    
    
    
    
    /*
    void venta(){
    
   
    
    
    //String sql="UPDATE videojuegos SET stock=stock-cantidad WHERE id_juegos="+id;
    String sql="UPDATE videojuegos SET stock=videojuegos.stock - factura.cantidad WHERE id_juegos="+id;
    try {
            
                 
                cn=con.getConnection();
                st=cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Registro en proceso");
                limpiartabla(model);
            

        } catch (HeadlessException | SQLException e) {
            
            System.err.print("Error:"+e);
        }
    
    
    
    }
    
    */
    
    
    
    void listacabecera(){
   
  String sql="select * from cabecerafactura order by cod_factura desc limit 1";
    
    try{
    
    cn=con.getConnection(); //la variable y metodo
    st=cn.createStatement();
     rs=st.executeQuery(sql);//ejecuta la consulta
     
     Object[]cabecerafactura=new Object[4]; // el 4 son los campos que contiene la tabla en la bd
     model = (DefaultTableModel)TablaFactu.getModel();
     
     while (rs.next()){
     
      cabecerafactura[0] = rs.getInt("cod_factura");
      cabecerafactura[1]=rs.getInt("CodigoCliente");
      cabecerafactura[2]=rs.getString("NombreEmpleado");
      cabecerafactura[3]=rs.getString("Fecha");
     
      
      
      
      model.addRow(cabecerafactura);
      
     
     }
     
     TablaFactu.setModel(model);
     
     
    } catch (SQLException e){
    
  System.err.print("Error:"+e);
    
    }
    
    }
    
    
    void listafactura(){
   
  String sql="select * from factura order by cod_factura desc limit 1";
    
    try{
    
    cn=con.getConnection(); //la variable y metodo
    st=cn.createStatement();
     rs=st.executeQuery(sql);//ejecuta la consulta
     
     Object[]factura=new Object[6]; // el 5 son los campos que contiene la tabla en la bd
     model = (DefaultTableModel)TablaFactu1.getModel();
     
     while (rs.next()){
     
      factura[0] = rs.getInt("cod_factura");
      factura[1]=rs.getInt("cod_producto");
      factura[2]=rs.getString("Nom_producto");
      factura[3]=rs.getInt("cantidad");
      factura[4]=rs.getString("precio");
      factura[5]=rs.getString("total");
     
      
      
      
      model.addRow(factura);
      
     
     }
     
     TablaFactu1.setModel(model);
     
     
    } catch (SQLException e){
    
  System.err.print("Error:"+e);
    
    }
    
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    void limpiartabla(DefaultTableModel model){
    
    for(int i=0;i<TablaDatos.getRowCount();i++){
    
        model.removeRow(i);
        i=i-1;
    
    }
    }
    
    
    
    
    
    
    
    
    
    
    
    
  
    

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

   /*
    
    
    void listafactura(){
   
  String sql="select * from factura order by id_factura desc limit 1";
    
    try{
    
    cn=con.getConnection(); //la variable y metodo
    st=cn.createStatement();
     rs=st.executeQuery(sql);//ejecuta la consulta
     
     Object[]factura=new Object[8]; // el 8 son los campos que contiene la tabla en la bd
     model = (DefaultTableModel)TablaFactu.getModel();
     
     while (rs.next()){
     
      factura[0] = rs.getInt("id_factura");
      factura[1]=rs.getInt("cod_cliente");
      factura[2]=rs.getString("nomproducto");
      factura[3]=rs.getString("cantidad");
      factura[4] =rs.getString("precio");
      factura[5] =rs.getString("fecha");
      factura[6] =rs.getString("total");
      
      
      
      model.addRow(factura);
      
     
     }
     
     TablaFactu.setModel(model);
     
     
    } catch (SQLException e){
    
  System.err.print("Error:"+e);
    
    }
    
    }
    
    */
    
    
    
    
    
    
   
   
    
  
    void venta2(){
    
   
    
    
    String sql="UPDATE factura SET total=precio * cantidad WHERE cod_factura=cod_factura";
    try {
            
                 
                cn=con.getConnection();
                st=cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, " articulo vendido");
                limpiartabla(model);
            

        } catch (HeadlessException | SQLException e) {
            
            System.err.print("Error:"+e);
        }
    
    
    
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /*
     void Imprimir(){
        
       
            
        String cli=txtcli.getText();
        String pro=txtnom.getText();
        String can=txtcan.getText();
        String sto=txtstock.getText();
        String pre=txtprecio.getText();
        String fe=txtfe.getText();
        String total=txtto.getText();
        
        
        
        if(cli.equals("")||pro.equals("")||can.equals("")||sto.equals("")||pre.equals("")||fe.equals("")||total.equals("")){
        
        JOptionPane.showMessageDialog(null,"¡debe llenar todos los campos!");
        limpiartabla(model);
        
        }else{
        String sql="insert into factura(cod_cliente,nomproducto,cantidad,stock,precio,fecha,total)values('"+cli+"','"+pro+"','"+can+"','"+sto+"','"+pre+"','"+fe+"','"+total+"')";
            try{
            
            cn=con.getConnection();
            st=cn.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showInternalMessageDialog(null,"Venta registrada");
            limpiartabla(model);
            
            } catch (SQLException e){
            
            System.err.print("Error:"+e);
            
            }
        
        
        }
        
        
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    */
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDatos;
    private javax.swing.JTable TablaFactu;
    private javax.swing.JTable TablaFactu1;
    private javax.swing.JTextField Total_art;
    private javax.swing.JTextField articulo_venta;
    private javax.swing.JTextField cant_art;
    private javax.swing.JTextField cod_factura;
    private javax.swing.JTextField cod_producto;
    private javax.swing.JTextField codigo_cliente;
    private javax.swing.JTextField fecha_fact;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nom_cliente;
    private javax.swing.JTextField nom_empleado;
    private javax.swing.JTextField num_factura;
    private javax.swing.JTextField preciu_unid;
    private javax.swing.JButton reg_factura;
    private javax.swing.JTextField stock_art;
    // End of variables declaration//GEN-END:variables
}
